#!/bin/sh
#
#autor: zb
#argc=0

#获取上一次提交的commit id
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

#重定向标准输出到标准错误
exec 1>&2

# 检测文件名
# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.

#检测代码是否规范
#需要indent
INDENT_CMD="indent -linux -bls -blf -bl -bli0"

file_list=$(git diff --cached --name-only|grep -E "*\.c|*\.h|*\.cpp|*\.hpp|*\.cxx|*\.hxx")
echo "use [indent -linux -bls -blf -bl -bli0 ] check... "
for file in $file_list
do
        tempfile=$(mktemp $file.XXXXXXXXXX)

        cat $file | $INDENT_CMD -o $tempfile
        diff -Nu $file $tempfile
        diff_res=$?
        rm $tempfile

        if ! [ $diff_res -eq 0 ]
        then
                cat <<EOF
$file bad

you need used

        'indent -linux -bls -blf -bl -bli0 $file '
or

        'cat $file | $INDENT_CMD -o $file'
EOF
                exit 1
        fi
done

# 检测是否有行尾空格
exec git diff-index --check --cached $against --
