#!/bin/bash

#set -x


print_error_1_info()
{
cat <<-EOF
##############################################################################
##                                                                          ##
## Commit message style check                                               ##
##                                                                          ##
## Example:                                                                 ##
##     <type>(<scope>): <subject>                                           ##
##                                                                          ##
##           <body>                                                         ##
##                                                                          ##
##     <footer>                                                             ##
##                                                                          ##
## <type>      Must be follow one :                                         ##
## 	         "feat","fix","docs","style","refactor","test","chore"      ##
##                                                                          ##
## <scope>     用于说明 commit影响范围                                      ##
##                                                                          ##
## <subject>   commit 目的的简短描述,不超过50个字符                         ##
##                                                                          ##
## <Footer>    如果当前代码与上一个版本不兼容                               ##
##             则 Footer 部分以BREAKING CHANGE开头                          ##
##                                                                          ##
## <Revert>    如果当前 commit 用于撤销以前的 commit                        ##
##             则必须以revert:开头,后面跟着被撤销 Commit 的 Header          ##
##                                                                          ##
##                                                                          ##
##############################################################################
EOF
}

print_error_2_info()
{
        cat <<-EOF
第二行必须是空行
EOF
}


#读取提交信息文件,删除文件中的注释行

sed -i '/^#/d' $1


linenum=1
breaknum=0

reg1='((^feat)|(^fix)|(^docs)|(^style)|(^refactor)|(^test)|(^chore))'

cat $1 | while read line
do

        case $linenum in
                1)
                        res=$(echo $line|grep -E ''$reg1'([\(]\w+[\)]){0,1}\:.+')
                        if [ -z "$res" ]
                        then
                                breaknum=1
                        fi
                        ;;
                2)
                        if ! echo $line | grep -E "^$"
                        then
                                breaknum=2
                        fi
                        ;;
        esac

        if [ $breaknum -ne 0 ]
        then
                print_error_"$breaknum"_info
                echo "commit massage error"
                exit 1
        fi

        linenum=$(( $linenum + 1 ))
done


#for debug
#echo "commit ok"
#exit 1
